services:
  ratiosplit-app:
    image: ghcr.io/gergokiss-ctrl/ratiosplit:latest
    container_name: ratiosplit-app
    restart: unless-stopped
    environment:
      DATABASE_URL: file:/data/ratiosplit.db
      APP_BASE_CURRENCY: HUF
      APP_DEFAULT_LOCALE: en-US
      APP_TIMEZONE: Europe/Budapest
    ports:
      - "3003:3000"
    volumes:
      - /mnt/user/appdata/ratiosplit/data:/data
